version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      - DATABASE_PATH=/app/database/conduit.sqlite
      - SESSION_SECRET=agamnestjshtmx
      - PORT=3000
